### ISSUE TITLE
The plugin can't fetch changes

### ISSUE THREAD

**Issue by lukyanov** [ashwanthkumar/gocd-slack-build-notifier#106]
Here is the error I get in the server logs when my pipeline fails:

```
jvm 1    | 2020-03-07 22:15:06,056  WARN [162@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.SlackPipelineListener:102 [plugin-slack.notifier] - Couldn't fetch changes
jvm 1    | java.io.FileNotFoundException: http://localhost:8153/go/api/pipelines/tp-core-PR-build/instance/22
jvm 1    | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
jvm 1    | 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
jvm 1    | 	at java.base/java.net.URLConnection.getContent(Unknown Source)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.jsonapi.Server.getUrl(Server.java:68)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.jsonapi.Server.getPipelineInstance(Server.java:89)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.GoNotificationMessage.fetchChanges(GoNotificationMessage.java:221)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.SlackPipelineListener.slackAttachment(SlackPipelineListener.java:111)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onFailed(SlackPipelineListener.java:57)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$3.handle(PipelineStatus.java:31)
```

The interesting thing is that when I make `curl http://localhost:8153/go/api/pipelines/tp-core-PR-build/instance/22` it works.

GoCD version: 20.1.0
Plugin version: 2.0.1

**Comment by ashwanthkumar** [comment]
Would you be kind enough to please try the jar as part of https://github.com/ashwanthkumar/gocd-slack-build-notifier/pull/107 and let me know if that fixes the issue?

**Comment by lukyanov** [comment]
Just checked. It's failing with the same error.

**Comment by nicolaasuni** [comment]
Unfortunately it doesn't fix the issue:
```
2020-03-09 09:21:31,457 WARN  [169@MessageListener for PluginNotificationMessageListener] SlackPipelineListener:102 - Couldn't fetch changes
java.io.FileNotFoundException: http://localhost:8153/go/api/pipelines/GOCD_BACKUP/instance/66
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.URLConnection.getContent(Unknown Source)
	at in.ashwanthkumar.gocd.slack.jsonapi.Server.getUrl(Server.java:69)
	at in.ashwanthkumar.gocd.slack.jsonapi.Server.getPipelineInstance(Server.java:90)
	at in.ashwanthkumar.gocd.slack.GoNotificationMessage.fetchChanges(GoNotificationMessage.java:221)
	at in.ashwanthkumar.gocd.slack.SlackPipelineListener.slackAttachment(SlackPipelineListener.java:111)
	at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onPassed(SlackPipelineListener.java:50)
	at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$2.handle(PipelineStatus.java:22)
	at in.ashwanthkumar.gocd.slack.PipelineListener.handlePipelineStatus(PipelineListener.java:37)
	at in.ashwanthkumar.gocd.slack.PipelineListener.notify(PipelineListener.java:26)
	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:83)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:44)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ashwanthkumar** [comment]
Ah! From the [documentation](https://api.gocd.org/current/#comment-on-pipeline-instance), it looks like the URL has changed. They seem to have dropped the `/instance/` from the URL. 

Please try this version that has the URI fix 

Build: [gocd-slack-notifier-2.0.2-RC2.jar.zip](https://github.com/ashwanthkumar/gocd-slack-build-notifier/files/4306059/gocd-slack-notifier-2.0.2-RC2.jar.zip)

#### Checksums
```
b91ec6ab4b71534740f47849d8ac04fe2c4ec97c387510934941a8bbec7a65e7  gocd-slack-notifier-2.0.2-RC2.jar
73f836afef47cb9403acb0f72e0f5db03239ff70f5622eaabf230928a9ba2d0d  gocd-slack-notifier-2.0.2-RC2.jar.zip
```

**Comment by lukyanov** [comment]
It looks like with this build the section "Changes" disappeared in the slack message.

**Comment by lukyanov** [comment]
Oh, sorry. It actually works now! I was just triggering pipelines without changes.

**Comment by ashwanthkumar** [comment]
Great thanks for testing. I'll cut a release with those changes shortly.

**Comment by ashwanthkumar** [comment]
This is fixed as part of https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v2.0.2.

**Comment by lukyanov** [comment]
@ashwanthkumar This new build with version 2.0.2 doesn't work :)
```
jvm 1    | 2020-03-11 06:08:47,247  INFO [162@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.GoNotificationPlugin:72 [plugin-slack.notifier] - tp-core-PR-docker/28/build/1 has Failed/Failed
jvm 1    | 2020-03-11 06:08:47,248  INFO [162@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.GoNotificationPlugin:77 [plugin-slack.notifier] - tp-core-PR-docker/28/build/1 failed with error
jvm 1    | java.lang.NullPointerException: null
jvm 1    | 	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
jvm 1    | 	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:83)
jvm 1    | 	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:44)
jvm 1    | 	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:29)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ashwanthkumar** [comment]
@lukyanov Seems like some kind of race condition. Can you try restarting the Go-Server once to make sure you still get the error?

**Comment by lukyanov** [comment]
I tried several times but still experiencing this.

**Comment by ashwanthkumar** [comment]
I'm not sure what's happening then. The error points to the fact that SlackListener implementation is not loaded properly. This most of the times in my experience points to an issue with Configuration file. Either invalid / not found / not readable, etc.

**Comment by lukyanov** [comment]
You were right, it was due to the configuration.

This is what causes it:
```
  pipelines = [{
    name = ".*"
    stage = ".*"
    group = ".*"
    state = ".*"
  }]
```
A add this part to the end of my config file. When I remove this, everything works. Is this considered wrong?

**Comment by arvindsv** [comment]
@lukyanov According to the documentation `state` should be `all`, rather than `.*`. Maybe try that?

Disclaimer: I don't use this plugin. Just someone curious. So, if it doesn't work, someone else will need to help.
