### ISSUE TITLE
No configuration setting found for key 'name'

### ISSUE THREAD

**Issue by atownsend-iotic** [ashwanthkumar/gocd-slack-build-notifier#109]
Running into the following error message when trying to configure different pipelines for slack messages. 

```
jvm 1    | 2020-09-02 12:16:44,339  INFO [Timer-0] p.s.n.i.a.g.s.GoNotificationPlugin:72 [plugin-slack.notifier] - Reloading configuration file since some modifications were found                             │
│ jvm 1    | 2020-09-02 12:16:44,341 ERROR [Timer-0] p.s.n.i.a.g.s.GoNotificationPlugin:127 [plugin-slack.notifier] - No configuration setting found for key 'name'                                               │
│ jvm 1    | com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'name'                                                                                                           │
│ jvm 1    |     at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)                                                                                                                          │
│ jvm 1    |     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)                                                                                                                             │
│ jvm 1    |     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)                                                                                                                             │
│ jvm 1    |     at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)                                                                                                                             │
│ jvm 1    |     at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)                                                                                                                        │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.PipelineRule.fromConfig(PipelineRule.java:169)                                                                                                            │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:289)                                                                                                                             │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:287)                                                                                                                             │
│ jvm 1    |     at in.ashwanthkumar.utils.collections.Lists.map(Lists.java:29)                                                                                                                                   │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.Rules.fromConfig(Rules.java:287)                                                                                                                          │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:27)                                                                                                                     │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:35)                                                                                                                     │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.read(RulesReader.java:17)                                                                                                                     │
│ jvm 1    |     at in.ashwanthkumar.gocd.slack.GoNotificationPlugin$1.run(GoNotificationPlugin.java:67)                                                                                                          │
│ jvm 1    |     at java.base/java.util.TimerThread.mainLoop(Unknown Source)                                                                                                                                      │
│ jvm 1    |     at java.base/java.util.TimerThread.run(Unknown Source)   
```
Here's my current config 

```
gocd.slack {
    login = "slack"
    password = "password"
    
    server-host = "https://buildhost/"
    api-server-host = "http://localhost:8153/"
    webhookUrl = "https://hooks.slack.com/services/XXXXXXXXX"
    process-all-rules = true

    pipelines = [{
      group = "dev"
      stage = ".*"
      state = "failed|passed"
      channel = "#dev-pipelines"    
      webhookUrl = "https://hooks.slack.com/services/YYYYYYYYYYYYYYY" 
      slackDisplayName = "gocd-slack-bot"
      slackUserIconURL = "https://www.looktothestars.org/photo/2188-terry-wogan/teaser-1503161742.jpg"
      display-console-log-links = true
      displayMaterialChanges = true      
    },
    {
      name = ".*"
      stage = ".*"
      state = "failed|passed"
      channel = "#build-pipelines"
      slackDisplayName = "gocd-slack-bot"
      slackUserIconURL = "https://www.looktothestars.org/photo/2188-terry-wogan/teaser-1503161742.jpg"
      display-console-log-links = true
      displayMaterialChanges = true
    }]
}
```

I'm using v2.0.2 of the plugin and GoCD is v20.1.0.

I'm trying to get anything in the dev group to post to a different channel but it fails. Messages to the build-pipelines channel continue to work. Any clues?

**Comment by atownsend-iotic** [comment]
I think this may actually be resolved now. For anyone searching, I added a name = "blah*" to the first pipeline and it started to work.
