### ISSUE TITLE
I only got the first notification in slack of a newly created pipeline

### ISSUE THREAD

**Issue by oenriqu1** [ashwanthkumar/gocd-slack-build-notifier#14]
I only got the first message in slack of a failure when creating the pipeline. For anything else I'm only getting errors.
I'm getting similar error messages in the logs as in issue: https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/6
However, I already have installed version 1.

From go-server.log
2015-07-08 08:23:20,756  WARN [69@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure"}']
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
    at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure"}'
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
    ... 8 more

From plugin-slack.notifier.log: 
2015-07-08 08:23:00,423  INFO [69@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Habanero/14/build/1 has Building/Unknown
2015-07-08 08:23:00,423  WARN [69@MessageListener for PluginNotificationListener] PipelineListener:62 - Couldn't find any matching rule for Habanero/build with status=Unknown
2015-07-08 08:23:20,537  INFO [69@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Habanero/14/build/1 has Failed/Failed

**Comment by oenriqu1** [comment]
The issue was solved after adding an Authentication mechanism. It seems the user: "anonymous" was causing the errors.
