### ISSUE TITLE
Null pointer exception with minimal config

### ISSUE THREAD

**Issue by argha-c** [ashwanthkumar/gocd-slack-build-notifier#23]
Hey,

We tried using the minimal config 

```
gocd.slack {
  login = "foo"
  password = "foo-bar"
  server-host = "https://go-instance:8153/"
  webhookUrl = "http://slack-instance.net/"

  pipelines = [{
    name = ".*"
    stage = ".*"
    state = "failed"
    channel = "#foo"
  }]
```

The exception stack trace we see is as below:

2015-11-30 15:43:36,718  INFO [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - test-pipeline/2/build/1 has Failed/Failed
2015-11-30 15:43:36,718 ERROR [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:77 - Error handling status message
java.lang.NullPointerException
    at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:77)
    at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:53)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
    at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
r

Could you help understand which config value we're missing here?
Thanks

**Comment by ashwanthkumar** [comment]
Can you please also include the GoCD and plugin version you're using.

**Comment by argha-c** [comment]
Go Version: 15.2.0
slack-notifier-1.1.1

**Comment by ashwanthkumar** [comment]
And the config file is located on the home folder right? Also the config you pasted is missing a closing `}` at the end, I suppose that's just a copy-paste issue?

**Comment by argha-c** [comment]
Yup, the closing brace is a copy/paste issue.
The file does exist in the expected directory path - /data/go-server/home

**Comment by ashwanthkumar** [comment]
That's the home folder location for user running go server, is it? Ok. 

Can you try adding this line to your config 

```
gocd.slack {
  // your usual configurations
  listener = "in.ashwanthkumar.gocd.slack.SlackPipelineListener"
}
```

**Comment by argha-c** [comment]
No luck. Tried with the updated config. Same error, same line.

**Comment by ashwanthkumar** [comment]
You had to restart the Go Server after the change for the plugin to pick it up. 

Give me couple of days. I'll try to get a new patched version with more logs so we can debug further. Meanwhile if you're interested to pick it up, [this line](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/java/in/ashwanthkumar/gocd/slack/ruleset/Rules.java#L169) is where I'm suspecting something is happening. The exception is actually IGNORED, instead we should throw a RuntimeException there and fail.

**Comment by argha-c** [comment]
I spin up a new container every time, and verified the modified config file was indeed available at the expected location.

Thanks for the help. Do keep us posted.

**Comment by argha-c** [comment]
@ashwanthkumar : Hey! Is a patch available for this issue?

**Comment by juhasipo** [comment]
@argha-c The exception from your minimal config seems to be `java.lang.IllegalArgumentException: Slack Webhook url starts with https://hooks.slack.com/services/`

@ashwanthkumar You're right that the [line](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/java/in/ashwanthkumar/gocd/slack/ruleset/Rules.java#L169) causes the actual error to be ignored which then causes the NullPointerException when the `getPipelineListener()` is called.

**Comment by ashwanthkumar** [comment]
@argha-c I'm sorry for getting back late on this. We now have a [release](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.2.1) (v1.2.1) which actually fails on that error line instead of silently failing elsewhere. Please do try it out and let me know if that helps.

**Comment by argha-c** [comment]
@ashwanthkumar Cool, thanks for the fix. Will take a look.

**Comment by ashwanthkumar** [comment]
Closing this. @argha-c Please feel free to re-open the issue if the issue occurs again.

**Comment by argha-c** [comment]
Sure, thanks for looking into this!
