### ISSUE TITLE
Getting - Error handling status message

### ISSUE THREAD

**Issue by rkrishna-1975** [ashwanthkumar/gocd-slack-build-notifier#30]
Using the plugin with 16.1.0 

I am getting the following message:

``` javascript
2016-02-19 13:28:11,615  INFO [73@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - cdp/233/Build/8 has Passed/Passed
2016-02-19 13:29:34,813 ERROR [73@MessageListener for PluginNotificationListener] GoNotificationPlugin:77 - Error handling status message
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:637)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1093)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
        at in.ashwanthkumar.slack.webhook.service.SlackService.execute(SlackService.java:55)
        at in.ashwanthkumar.slack.webhook.service.SlackService.push(SlackService.java:43)
        at in.ashwanthkumar.slack.webhook.Slack.push(Slack.java:98)
        at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onPassed(SlackPipelineListener.java:40)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$2.handle(PipelineStatus.java:22)
        at in.ashwanthkumar.gocd.slack.PipelineListener.handlePipelineStatus(PipelineListener.java:31)
        at in.ashwanthkumar.gocd.slack.PipelineListener.notify(PipelineListener.java:24)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:77)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:53)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
```

my config is :  

``` javascript
gocd.slack {
# Go Server information
  login = "XXXXXX"
  password = "XXXXX"
  #server-host = "http://ci.XXXXX.com/"
  server-host = "http://127.0.0.1:8153/"
  webhookUrl = "https://hooks.slack.com/services/TTTTTTTTTTT/XXXXXXXXXXXXXXXXXX"

# optional fields
 channel = "#XXXXXX"
#  slackDisplayName = "gocd-slack-bot"
#  slackUserIconURL = "https://www.go.cd/images/logo-go-home_2014.png"
  pipelines = [{
   name = ".*"
   stage = ".*"
   state = "all"
  }]
}
```

**Comment by ashwanthkumar** [comment]
@rkrishna-1975 Seems like an internet issue on your side. Does your CI machine has access to internet? Can you also check if you're able to ping `hooks.slack.com` ?

**Comment by rkrishna-1975** [comment]
It is behind a proxy. I have added the Java startup properties for proxyHost and others. I am able to submit to webhooks using curl from the machine.

**Comment by ashwanthkumar** [comment]
I haven't tested the plugin in a Proxy based environment. Looks like your issue is similar to https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/2. Since slack hooks is served under https, make sure `https.proxyHost` and `https.proxyPort` apart from the `http` variants of the above. 

AFAIK if your Go Server is able to talk to internet via JVM properties, then plugin should be able to do it as well, since they run inside the same JVM.

**Comment by rkrishna-1975** [comment]
It was the https proxy. I thought that we did not need a proxy for https but putting in the https proxy solved the issue. Thanks closing the issue.

**Comment by GenoZhou** [comment]
@rkrishna-1975 I got the same error, Just wonder how you solve this issue by putting  in the https proxy?
I tried adding following content in /etc/default/go-server but it does not work

```
export GO_SERVER_SYSTEM_PROPERTIES="-Dhttp.proxyHost=http://proxy.xxx.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=http://proxy.xxx.com -Dhttps.proxyPort=8080"
```
