### ISSUE TITLE
Trying to connect to Rocket.Chat

### ISSUE THREAD

**Issue by gtrias** [ashwanthkumar/gocd-slack-build-notifier#36]
I've just installed this plugin (v1.2.0) to go-server (v16.1.0). And setting up to send the notifications to Rocket.Chat slack's compatible API.

my go_notify.conf

```
gocd.slack {
  login = "rocketchat"
  password = "valid-go-server-user-pass"
  server-host = "http://localhost:8153/"
  webhookUrl = "Provided valid rocket.chat integration url"
}
```

And I'm getting this error when the plugin tries to send the notification:

```
2016-03-14 14:58:07,714  WARN [69@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}']
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:38)
    at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}'
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:36)
    ... 8 more
```

Any idea what could I do wrong?

**Comment by ashwanthkumar** [comment]
@gtrias Can you share the plugin logs? It might contains some information to debug this.

**Comment by gtrias** [comment]
sure, this are my logs inside `plugin-slack.notifier.log`

```
2016-03-14 15:03:19,779  INFO [69@MessageListener for PluginNotificationListener] GoNotificationPlugin:57 - xxxxx-api/27/deploy/9 failed with error
java.lang.NullPointerException
    at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:121)
    at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:59)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
    at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by ashwanthkumar** [comment]
Looks like the plugin init failed. Is the go_notify.conf present on the go user's home directory? 

My guess is this should have kicked in - https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/src/main/java/in/ashwanthkumar/gocd/slack/GoNotificationPlugin.java#L45 - Do you see any RTE in the plugin logs?

**Comment by gtrias** [comment]
I have already `go_config.conf` present in my go's user home (/var/go). And I didn't see this error of file not found in the logs.

**Comment by juhasipo** [comment]
The cause is probably the same as in the issue #23. Exception `java.lang.IllegalArgumentException: Slack Webhook url starts with https://hooks.slack.com/services/` is thrown by the slack-java-webhook library so the Pipeline Listener never gets initialized but the exception never ends up in the log.

**Comment by ashwanthkumar** [comment]
@gtrias I've made a release (https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.2.1) removing that check from the underlying slack client library - so hopefully it can also be used for Rocket.Chat. Can you please verify if the latest v1.2.1 version helps you solve the issue?

**Comment by ashwanthkumar** [comment]
Thank you so much for the pointer @juhasipo :+1:

**Comment by gtrias** [comment]
Yeah it works like charm!! Thank you so much :)

**Comment by pasmon** [comment]
@gtrias Sorry I'm late to the game, but care to share the integration script you are using to get this working? I'm failing to access and print the information of attachments properly in our Rocket.Chat.
