### ISSUE TITLE
Plugin Error after Go Server Upgrade

### ISSUE THREAD

**Issue by dayglojesus** [ashwanthkumar/gocd-slack-build-notifier#41]
##### Began receiving the following error after upgrading Java and Go:

```
2016-04-19 02:23:34,800  WARN [68@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"],"status":"failure"}']
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:38)
    at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
    at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"],"status":"failure"}'
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:36)
    ... 8 more
```
##### Java Version

```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```
##### GoCD Version

```
Go Version: 16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)
```

**Comment by ashwanthkumar** [comment]
Looks like Go can't access your default CA Certifacte store for some reason. Possible permissions issue? Please check if [this solution](http://stackoverflow.com/a/30699960/1058334) helps.

**Comment by dayglojesus** [comment]
Thanks for the quick reply. I will review this ASAP. Cheers.

**Comment by dayglojesus** [comment]
Thanks @ashwanthkumar that was the fix. Cheers!
