### ISSUE TITLE
Notification update failed for plugin: slack.notifier

### ISSUE THREAD

**Issue by kkoppel** [ashwanthkumar/gocd-slack-build-notifier#6]
Hi!

I'm trying to use release 0.1 of your plugin with Go v15.1. I have created the /var/go/go_notify.conf file as follows:

```
gocd.slack {
  server-host = "https://my.gocd.url/"
  webhookUrl = "https://hooks.slack.com/services/SOMEHASH"
  channel = "#updates"
}
```

The following error is logged in the Go server log on every pipeline run (even successful ones):

```
2015-05-12 08:55:18,914  WARN [64@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":[null]}']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":[null]}'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 8 more
```

The following line is also logged in plugin-slack.notifier.log every time:

```
2015-05-12 08:55:18,914  INFO [64@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - null/null/null/null has null/null
```

Any idea why this might be happening?
BTW, I can manually post messages using the configured Slack URL.

**Comment by ashwanthkumar** [comment]
@kkoppel Can you try with the 0.2 version of the plugin? 
https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/0.2

**Comment by kkoppel** [comment]
I get some more informative errors now. In the Go server log:

```
2015-05-12 10:13:19,460  WARN [64@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus.UNKNOWN"]}']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '{"status":"failure","messages":["No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus.UNKNOWN"]}'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 8 more
```

And in plugin-slack.notifier.log:

```
2015-05-12 10:12:57,852  INFO [64@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Testing/748/trial/2 has Building/Unknown
2015-05-12 10:13:19,300  INFO [64@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Testing/748/trial/2 has Passed/Passed
2015-05-12 10:13:19,301  WARN [64@MessageListener for PluginNotificationListener] PipelineListener:62 - Couldn't find any matching rule for Testing/trial with status=Passed
2015-05-12 10:13:19,460  INFO [64@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Testing/748/deploy2testing/2 has Building/Unknown
2015-05-12 10:13:36,452  INFO [64@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - Testing/748/deploy2testing/2 has Passed/Passed
2015-05-12 10:13:36,453  WARN [64@MessageListener for PluginNotificationListener] PipelineListener:62 - Couldn't find any matching rule for Testing/deploy2testing with status=Passed
```

**Comment by ashwanthkumar** [comment]
This helps. Let me have a look tonight and get back to you on this.

**Comment by ashwanthkumar** [comment]
Can you try the new v1.0 release? There was a pending PR which fixed (most of) these issues.

**Comment by kkoppel** [comment]
Hi!

It works fine now. Thanks a lot for the fast response!

**Comment by abhayda** [comment]
I m still facing this issue with latest Go server 

Error - Notification update failed for plugin: slack.notifier29 Nov, 2018 at 16:21:45 Local Time

Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["Connection refused (Connection refused)"],"status":"failure"}']

Builds -
GoCD Version: 18.11.0-8024
Plugin - v1.4.0-RC11

**Comment by sandeeprapido** [comment]
@abhayda +1 

@ashwanthkumar Facing this issue in Gocd Version : 19.5.0 and Plugin Version v1.4.0
