### ISSUE TITLE
Unable to send notification

### ISSUE THREAD

**Issue by hosh** [ashwanthkumar/gocd-slack-build-notifier#63]
```
Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}']
```

```
2016-11-18 20:54:50,018  INFO [Thread-69] GoNotificationPlugin:52 - Configuration file found at Home Dir as /var/go/go_notify.conf
2016-11-18 20:54:50,019  INFO [Timer-0] GoNotificationPlugin:52 - Loading configuration file
2016-11-18 20:54:50,342 ERROR [Timer-0] GoNotificationPlugin:77 - No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus..*
java.lang.IllegalArgumentException: No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus..*
        at java.lang.Enum.valueOf(Enum.java:236)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus.valueOf(PipelineStatus.java:6)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineRule.fromConfig(PipelineRule.java:157)
        at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:259)
        at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:257)
        at in.ashwanthkumar.utils.collections.Lists.map(Lists.java:29)
        at in.ashwanthkumar.gocd.slack.ruleset.Rules.fromConfig(Rules.java:257)
        at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:27)
        at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:35)
        at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.read(RulesReader.java:17)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin$1.run(GoNotificationPlugin.java:67)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2016-11-18 21:00:51,514  INFO [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 - legalio-rails/6/Deploy/2 has Passed/Passed
2016-11-18 21:00:51,515  INFO [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:57 - legalio-rails/6/Deploy/2 failed with error
java.lang.NullPointerException
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:186)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:181)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:181)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:69)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
```

The configuration looks like this:

```
gocd.slack {
  login = "XXXXX"
  password = "XXXXXXX"
  server-host = "http://localhost:8153/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/XXXX/XXXX/XXXX"

  # optional fields
  channel = "#dev-notification"
  slackDisplayName = "gocd"
  display-console-log-links = true
  displayMaterialChanges = true
  process-all-rules = false

  pipelines = [{
     name = "legalio-rails"
     stage = ".*"
     state = ".*"
     channel = "#dev-notifications"
   }]
}
```

Java version:
```
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
```

**Comment by jdavisp3** [comment]
The `state` parameter is not a regex, it's a `|`-separated list.

```
state - State of the pipeline at which we should send a notification. You can provide multiple values separated by pipe (|) symbol. Valid values are passed, failed, cancelled, building, fixed, broken or all.
```

**Comment by hosh** [comment]
Gotcha, going to try this, thanks!

**Comment by ashwanthkumar** [comment]
@hosh I'm closing this issue now. Please feel free to re-open if the issue persists.

**Comment by hosh** [comment]
Solution suggested worked.
