### ISSUE TITLE
Has this broken in GoCD 17.2?

### ISSUE THREAD

**Issue by Stono** [ashwanthkumar/gocd-slack-build-notifier#68]
Hey, 
I've noticed notifications aren't working in 17.2, and then also noticed this in the release notes:
https://github.com/gocd/gocd/commit/8f88269fd8165246820ad1c27685485dd3fe0627 

We haven't changed anything other than the gocd version, and I can't see anything in the logs so not sure where else to look!

I don't know enough about either code base to answer this myself, but the slack notifier is still listed as a plugin on the gocd plugins page.

I'm on RC10
Ta
Karl

**Comment by Stono** [comment]
In fact, a lamens look at the code probably looks like it has:
```
import com.thoughtworks.go.plugin.api.request.GoPluginApiRequest;
import com.thoughtworks.go.plugin.api.response.GoPluginApiResponse;
```

Shame, as this is a super important plugin for the teams i use it on :(

**Comment by Stono** [comment]
```
Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. 
Reason: [The plugin sent a response that could not be understood by Go. 
Plugin returned with code '500' and the following response: 
'{"messages":["java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"],"status":"failure"}']
```

**Comment by ashwanthkumar** [comment]
@Stono Searching the error leads me to this page on [StackOverflow](http://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty). Can you try if the solutions mentioned helps?

**Comment by Stono** [comment]
@ashwanthkumar give me a few minutes, as it's in docker I need to add this points and redeploy the container!  I will upgrade to RC11 whilst i'm at it

**Comment by ashwanthkumar** [comment]
This plugin is not based on old JAVA based API so it's not affected by the upgrade. On the error, it would be super nice if you can share more logs from the `plugin-slack.notifier.log` or `go-server.log` that's relevant to the error.

**Comment by Stono** [comment]
@ashwanthkumar give me a few minutes, as it's in docker I need to add this points and redeploy the container!  I will upgrade to RC11 whilst i'm at it

**Comment by Stono** [comment]
This is all I've got from the container
```
LOG: java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"],"status":"failure"}']
LOG: 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
LOG: 	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
LOG: 	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
LOG: 	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
LOG: 	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
LOG: 	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
LOG: 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
LOG: 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
LOG: 	at java.lang.Thread.run(Thread.java:745)
LOG: Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"],"status":"failure"}'
LOG: 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
LOG: 	... 8 more
LOG: 2017-03-20 19:05:08,314  INFO [consumeBuildCausesThread] ScheduleService:159 - [Pipeline Schedule] Scheduling pipeline e2e.thoughtdata.integration with build cause [ModificationBuildCause: triggered by e2e.thoughtdata/26/build/1]
LOG: 2017-03-20 19:05:08,346  INFO [consumeBuildCausesThread] PipelineRepository:85 - Start updating pipeline timeline
LOG: 2017-03-20 19:05:08,351  INFO [consumeBuildCausesThread] PipelineRepository:91 - Pipeline timeline updated
LOG: 2017-03-20 19:05:08,441  WARN [68@MessageListener for PluginNotificationListener] PluginNotificationService:78 - Notification update failed for plugin: slack.notifier
```

**Comment by ashwanthkumar** [comment]
Okay this the `go-server.log`. There's another file called `plugin-slack.notifier.log` in the same directory. Probably that's not piped to STDOUT (for obvious reasons). If you can ssh into the container you should be able to see it. Also you should try the solution of installing custom packages in the container to see if that helps. Not sure what docker container you're using and what version of JVM it runs on.

**Comment by Stono** [comment]
@ashwanthkumar I'm using https://github.com/Stono/gocd-master/blob/master/Dockerfile which is basically the 'gocd image' produced by tw, with a couple of extras that i want (like this plugin).

No plugin logs:
```
root@gocd-master-4277714432-jxk1f:/var/log/go-server# ls -lah
total 12K
drwxrwsrwx 2 go   go     4.0K Mar 20 18:30 .
drwxrwxr-x 1 root syslog 4.0K Mar 20 18:30 ..
lrwxrwxrwx 1 root go       36 Mar 20 18:30 go-server.log -> /var/log/go-server/go-server.out.log
-rw-r--r-- 1 go   go      515 Mar 20 18:30 go-server.out.log
```

**Comment by Stono** [comment]
@ashwanthkumar the two certificate lines fixed it! I'll update the issue on go as you probably want this in the main container.
