### ISSUE TITLE
Error while sending notifications: Unable to find valid certification

### ISSUE THREAD

**Issue by ghost** [ashwanthkumar/gocd-slack-build-notifier#81]
Good adternoon, I'm getting this error while trying to send a notification:

![image](https://user-images.githubusercontent.com/23528701/39263848-be4c0092-4899-11e8-8869-e12a749924a9.png)

Here it is the go_notify.conf (the login and password are the ones to log on the Go Cd machine)
![image](https://user-images.githubusercontent.com/23528701/39263962-fb3b2a46-4899-11e8-9771-52a13b68d044.png)

I'm trying to find related issues or solutions for this. Could you help me, please?

**Comment by vyomrastogi** [comment]
Facing same issue for sometime now. 
error from logs 
```
2018-04-30 17:57:42,504  INFO [75@MessageListener for PluginNotificationListener] GoNotificationPlugin:57 - service/23/performance-test/1 failed with error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
        at in.ashwanthkumar.slack.webhook.service.SlackService.execute(SlackService.java:69)
        at in.ashwanthkumar.slack.webhook.service.SlackService.push(SlackService.java:56)
        at in.ashwanthkumar.slack.webhook.Slack.push(Slack.java:129)
        at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onFailed(SlackPipelineListener.java:58)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$3.handle(PipelineStatus.java:31)
        at in.ashwanthkumar.gocd.slack.PipelineListener.handlePipelineStatus(PipelineListener.java:37)
        at in.ashwanthkumar.gocd.slack.PipelineListener.notify(PipelineListener.java:26)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:166)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:161)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:161)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
        ... 37 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
        ... 43 more
```

Need some insight on what to check or how to resolve ?

**Comment by ashwanthkumar** [comment]
Sorry for the late response on this one. This error usually happens when JDK is not able to validate the destination HTTPS certificate. 

If you're using a latest JDK this should not be a problem generally. Another reason why this might occur is, do you've a proxy in your environment? Either an explicit or an implicit one? If a proxy is doing a MITM for HTTPS connections, then the certificate returned by the proxy might be a self-signed one. Which might cause this issue. 

---

On verifying the https `openssl`
```
$ openssl s_client -connect hooks.slack.com:443
CONNECTED(00000005)
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=CA/L=San Francisco/O=Slack Technologies, Inc./CN=slack.com
   i:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
 1 s:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
...
```

It looks Slack is using DigiCert's Root chain. According to [JDK8u91's release notes](http://www.oracle.com/technetwork/java/javase/8u91-relnotes-2949462.html), it was added into default trust store of JDK from that release onwards. So upgrading to use JRE versions greater than 1.8.0_u91, should solve the above problem. 

For the other type of issues where you've a transparent proxy consider following the steps outlined [here](https://www.mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/) to create a new custom trust store and add it as part of your JRE installation.

**Comment by hchemanchula** [comment]
I am using latest version of plugin and seeing similar issue. Any help could be appreciated..!!

```2018-05-01 17:06:44,952 WARN  [77@MessageListener for PluginNotificationListener] PluginNotificationService:79 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["https://localhost"],"status":"failure"}']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:57)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:87)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["https://localhost"],"status":"failure"}'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:55)
        ... 8 common frames omitted```

**Comment by ghost** [comment]
Thanks for the reply @ashwanthkumar. I will check the jdk version on our environment. I will check also with our infrastructure team about the proxy. I can't do this now, but as soon as I do it, I will inform on this issue. :)

**Comment by vyomrastogi** [comment]
> It looks Slack is using DigiCert's Root chain. According to JDK8u91's release notes, it was added into default trust store of JDK from that release onwards. So upgrading to use JRE versions greater than 1.8.0_u91, should solve the above problem.

Upgrading java for gocd server to JDK8u171 fixed the cert issue for me. Thanks for quick help.

**Comment by ashwanthkumar** [comment]
@vyomrastogi Thanks for the update. Glad it worked out. 

@hchemanchula Can you please post the plugin logs?

**Comment by ghost** [comment]
@ashwanthkumar upgraded the jdk version to JDK8u171 as @vyomrastogi  did and the problem still occurs. I will investigate the proxy question. Any hints on what to do if it is a proxy related issue?

**Comment by ashwanthkumar** [comment]
@hbsis-williamdasilva Silly question - Did you try restarting the Go Server post the JDK installation? 

If it's a proxy related issue,

> For the other type of issues where you've a transparent proxy consider following the steps outlined [here](https://www.mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/) to create a new custom trust store and add it as part of your JRE installation.

**Comment by ghost** [comment]
@ashwanthkumar not a silly question at all, since my team mate who upgraded the jdk did not restart the Go Server haha

But I did it right now and still get the exception. Starting to think this is a proxy related. I'm talking with the Infrastructure guys. Any info and I'll inform you. Thanks :)

**Comment by ghost** [comment]
@ashwanthkumar Found a little guy hidden here: 
![image](https://user-images.githubusercontent.com/23528701/39589888-cb04e79e-4ed5-11e8-90f0-17dd44612aeb.png)

Does this plugin works only for github repositories? We were using github but migrated to bitbucket.
Could this be the problem?

**Comment by ashwanthkumar** [comment]
@hbsis-williamdasilva No that shouldn't be a problem. You might not get a pretty URL in the slack message but it shouldn't break the plugin's functionality.

Ref - Check [This](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/f7d27529b2525a8cd58fc02e9f32b7c8a4b1bfb9/src/main/java/in/ashwanthkumar/gocd/slack/jsonapi/MaterialRevision.java#L54-L60) and [that](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/25533ebba69d52a701a6e575089e6ec02b454325/src/main/java/in/ashwanthkumar/gocd/slack/SlackPipelineListener.java#L121).

**Comment by ghost** [comment]
Got it, thanks. So this is not the problem...

Ok, here is what we know: Our CI envoironment is HTTP and bitbucket is HTTPS. We are getting a SSL Handshake exception, so it is probably because we can't acces bitbucket. 
Things looks like it is not a problem with the notifier.
Thanks for your time @ashwanthkumar. I think we can close the issue now

**Comment by ghost** [comment]
@ashwanthkumar For the records, maybe this can help someone:

The problem was with the proxy/firewall, the machine could not connect to the Webhook from slack (wich is https). 
Problem solved

**Comment by ashwanthkumar** [comment]
Thanks @hbsis-williamdasilva for the update :+1:
