### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kirantech58** [ashwanthkumar/gocd-slack-build-notifier#82]
Error Am facing  Can you please help me  
```
2018-05-03 16:08:36,844  INFO [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:52 -  has Building/Unknown
2018-05-03 16:08:36,845  INFO [68@MessageListener for PluginNotificationListener] GoNotificationPlugin:57 -  failed with error
java.lang.NullPointerException
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:66)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
```

 java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by ashwanthkumar** [comment]
@kirantech58 Can you please share your configuration file that you're using? Please mask any sensitive details like URLs and credentials.

**Comment by kirantech58** [comment]
@ashwanthkumar 

here is my  configuration file

```
gocd.slack {
  login = "***"
  password = "***"
  server-host = "http://localhost:8153/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/"
  pipelines = [{
    name = ".*"
    stage = ".*"
    state = ".*"
    channel = "#***"
  }
  ]
  # optional fields
  channel = "#***"
  slackDisplayName = "Gocd"
  #slackUserIconURL = "http://example.com/slack-bot.png"
  display-console-log-links = true
  displayMaterialChanges = false
  process-all-rules = true
  truncate-changes = true
}
```

**Comment by kirantech58** [comment]
And Go Version: 16.1.0  and Slack-Notifier Version: gocd-slack-notifier-1.4.0-RC10.jar any Suggestion on changing .jar version.

**Comment by ashwanthkumar** [comment]
@kirantech58 The error points out that `listener` in the configuration is wrong. But from your config it looks like you've not changed it. 

Do you find any errors on the `plugin-slack.notifier.log` ? 

I'm looking for errors related to something like [this](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/025490e387329299bfbc11d29ea4e62a9c17497e/src/main/java/in/ashwanthkumar/gocd/slack/ruleset/Rules.java#L294-L299).

**Comment by hchemanchula** [comment]
Hi,

I am also facing same issue, please find the logs below:
```2018-05-15 14:34:00,461 INFO  [78@MessageListener for PluginNotificationListener] GoNotificationPlugin:77 - test/33/build-commit/1 failed with error
java.lang.NullPointerException: null
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:87)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Unknown Source)```

Any help is appreciated.


Thanks,
Hemanth

**Comment by ashwanthkumar** [comment]
@hchemanchula Can you please check the above [comment](https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/82#issuecomment-388290248) and find any relevant details on the logs before this error is thrown?

**Comment by hchemanchula** [comment]
@ashwanthkumar Hi, I am not seeing any exceptions related to the pipeline listener.

**Comment by ashwanthkumar** [comment]
@hchemanchula Is there any other exceptions apart from this one on the logs? Would it be possible for you to share the entire log file (after masking any sensitive information in it) here? 

Please also share the plugin version and GoCD version you're using.

**Comment by hchemanchula** [comment]
@ashwanthkumar I am using GoCD 18.2v and gocd-slack-notifier-1.4.0-RC10.  Not seeing any other exceptions in the log other than the null pointer exception. 

```2018-05-16 18:16:40,535 INFO  [79@MessageListener for PluginNotificationListener] GoNotificationPlugin:72 - test/59/build-commit/1 has Building/Unknown
2018-05-16 18:16:40,536 INFO  [79@MessageListener for PluginNotificationListener] GoNotificationPlugin:77 - test/59/build-commit/1 failed with error
java.lang.NullPointerException: null
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:87)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Unknown Source)
2018-05-16 18:17:35,925 INFO  [79@MessageListener for PluginNotificationListener] GoNotificationPlugin:72 - test/59/build-commit/1 has Failed/Failed
2018-05-16 18:17:35,926 INFO  [79@MessageListener for PluginNotificationListener] GoNotificationPlugin:77 - test/59/build-commit/1 failed with error
java.lang.NullPointerException: null
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:87)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Unknown Source)```

**Comment by matthias-k** [comment]
I experienced a similar (or likely the same) problem and it turned out that I accidentally had mounted the plugin configuration as `/home/go/go_notify.conf/go_notify.conf` instead of `/home/go/go_notify.conf` which meant that the plugin tried to read a directory. After I fixed the mount path, the nullpointer exceptions are gone.

**Comment by cfontes** [comment]
For some reason during the update this file was whipped clean.

I added the config again and it works!

Thanks!

**Comment by ashwanthkumar** [comment]
Closing the issue. Please re-open if you still have issues.
