### ISSUE TITLE
 Server returned HTTP response code: 401

### ISSUE THREAD

**Issue by kecondezo** [ashwanthkumar/gocd-slack-build-notifier#87]
I have the gocd-slack-notifier-1.4.0-RC11.jar plugin version on GoCD v18.8 (using a docker container).
This is my go_notify.conf file
```
gocd.slack {
login = "wakicorp@gmail.com"
password = "********"
server-host = "http://172.31.83.7:8153/"
api-server-host = "http://172.31.83.7:8153/"
  webhookUrl = "https://comufin.slack.com"
  channel = "#gocd"
  slackDisplayName = "gocd-slack-bot"
  display-console-log-links = true
  displayMaterialChanges = true
  process-all-rules = true
}
```

I know that the plugin is taking my configuration file because when I ran a pipeline I have this log in gocd server saying thet the api-server-host configured is returning 401 status but when i try it manually using curl command inside the server and inside the doker container (in both places) and I can get a sucess response. So why in go it is returning 401?

```
2018-09-26 16:41:12,520 INFO  [qtp733957003-25] ScheduleService:231 - [Stage Schedule] Scheduling stage test-docker-service for pipeline deploy-admision-web-dev
2018-09-26 16:41:12,894  INFO [140@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.GoNotificationPlugin:73 [plugin-slack.notifier] - deploy-admision-web-dev/21/test-docker-service/5 has Building/Unknown
2018-09-26 16:41:12,898  INFO [140@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.j.Server:73 [plugin-slack.notifier] - Fetching **http://172.31.83.7:8153/**go/api/pipelines/deploy-admision-web-dev/history
2018-09-26 16:41:13,016  WARN [140@MessageListener for PluginNotificationMessageListener] p.s.n.i.a.g.s.SlackPipelineListener:103 [plugin-slack.notifier] - Couldn't fetch build details
java.io.IOException: Server returned HTTP response code: 401 for URL: http://172.31.83.7:8153/go/api/pipelines/deploy-admision-web-dev/history
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.URLConnection.getContent(URLConnection.java:739)
        at in.ashwanthkumar.gocd.slack.jsonapi.Server.getUrl(Server.java:61)
        at in.ashwanthkumar.gocd.slack.jsonapi.Server.getPipelineHistory(Server.java:71)
        at in.ashwanthkumar.gocd.slack.GoNotificationMessage.fetchRecentPipelineHistory(GoNotificationMessage.java:139)
        at in.ashwanthkumar.gocd.slack.GoNotificationMessage.fetchDetailsForBuild(GoNotificationMessage.java:147)
        at in.ashwanthkumar.gocd.slack.GoNotificationMessage.fetchDetails(GoNotificationMessage.java:213)
        at in.ashwanthkumar.gocd.slack.SlackPipelineListener.slackAttachment(SlackPipelineListener.java:91)
        at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onBuilding(SlackPipelineListener.java:44)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$1.handle(PipelineStatus.java:13)
        at in.ashwanthkumar.gocd.slack.PipelineListener.handlePipelineStatus(PipelineListener.java:37)
        at in.ashwanthkumar.gocd.slack.PipelineListener.notify(PipelineListener.java:26)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:225)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:91)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ashwanthkumar** [comment]
@kecondezo Username credentials to the GoCD should be a direct user on the server. If you're using any auth plugins, then please use the default `admin` account.

**Comment by kecondezo** [comment]
Thank you you were right, but as I have no authentication implemented yet in gocd I had to left this user and password properties empty. Now I am reaching fine the gocd rest api.
After this I had another issue so I will chek if there is not a previous similar issue otherwise i will open another issue.
we can close this.
Thank you @ashwanthkumar
