### ISSUE TITLE
No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus..*

### ISSUE THREAD

**Issue by mbelchin** [ashwanthkumar/gocd-slack-build-notifier#89]
Hi,

today I made some configurations into my `go_notify.conf` file. Just added a new pipeline configuration to post messages to a certain slack channel for a new project.

After restarting server & agent I got this error for gocd-slack notifier plugin.

```
2018-10-31 15:45:57,428  INFO [Thread-75] GoNotificationPlugin:49 - Configuration file found at Home Dir as /home/go/go_notify.conf
2018-10-31 15:45:57,433  INFO [Timer-0] GoNotificationPlugin:49 - Loading configuration file
2018-10-31 15:45:57,692 ERROR [Timer-0] GoNotificationPlugin:74 - No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus..*
java.lang.IllegalArgumentException: No enum constant in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus..*
	at java.lang.Enum.valueOf(Enum.java:238)
	at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus.valueOf(PipelineStatus.java:6)
	at in.ashwanthkumar.gocd.slack.ruleset.PipelineRule.fromConfig(PipelineRule.java:157)
	at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:274)
	at in.ashwanthkumar.gocd.slack.ruleset.Rules$2.apply(Rules.java:272)
	at in.ashwanthkumar.utils.collections.Lists.map(Lists.java:29)
	at in.ashwanthkumar.gocd.slack.ruleset.Rules.fromConfig(Rules.java:272)
	at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:27)
	at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.load(RulesReader.java:35)
	at in.ashwanthkumar.gocd.slack.ruleset.RulesReader.read(RulesReader.java:17)
	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin$1.run(GoNotificationPlugin.java:67)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

My configuration looks like this:

```
gocd.slack {
  login = "slack_user"
  password = "somepassword"
  server-host = "https://cd.domain.io:8154/"
  api-server-host = "http://localhost:8153/"
  webhookUrl = "https://hooks.slack.com/services/someid"

  # optional fields
  channel = "#devteam"
  slackDisplayName = "gocd-slack-bot"
  display-console-log-links = true
  displayMaterialChanges = true
  process-all-rules = false

  pipelines = [{
    name = "api"
    stage = ".*"
    group = ".*"
    state = ".*"
    channel = "#cb_api"
  },
  ...  MORE projects like above one configured here ...
  {
    name = "cb_themes"
    stage = ".*"
    group = ".*"
    state = ".*"
    channel = "#cb_components"
  },
  {
    name = ".*"
    stage = ".*"
    group = ".*"
    state = "failed|passed"
  }]  
}

```

This is the new configuration added today.
``` 
{
    name = "cb_themes"
    stage = ".*"
    group = ".*"
    state = ".*"
    channel = "#cb_components"
  },
```

Whenever I run a new pipeline I see this error in **plugin-slack.notifier.log** 

```
2018-10-31 15:56:53,590  INFO [75@MessageListener for PluginNotificationListener] GoNotificationPlugin:49 - cb_themes/10/version/1 has Failed/Failed
2018-10-31 15:56:53,591  INFO [75@MessageListener for PluginNotificationListener] GoNotificationPlugin:54 - cb_themes/10/version/1 failed with error
java.lang.NullPointerException
	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
	at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)

```

And this error in **go-server.log**
```
2018-10-31 15:56:53,591  WARN [75@MessageListener for PluginNotificationListener] PluginNotificationService:79 - Notification update failed for plugin: slack.notifier
java.lang.RuntimeException: Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:42)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"status":"failure"}'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:40)
	... 8 more
```

No new versions installed or anything like that.

GoCD version 17.10
gocd-slack-build-notifier version : 1.4.0-RC10

Any suggestion on how to fix it and why suddenly it's failing ?

**Comment by ashwanthkumar** [comment]
@mbelchin `.*` in `state` is not the right value. If you want to send a notification for all the states, you might to consider using `all`. Can you please try changing the value of the `state = '.*'` to `state=all` and see if you still get an error?

**Comment by mbelchin** [comment]
You're totally right. After changing that value to `all` everything is working as expected.

Sorry for the noice @ashwanthkumar I was just probably to fast on copy/paste.
