### ISSUE TITLE
slack notification issue with latest GOCD again

### ISSUE THREAD

**Issue by abhayda** [ashwanthkumar/gocd-slack-build-notifier#90]
I m still facing this issue with latest Go server

Error - Notification update failed for plugin: slack.notifier29 Nov, 2018 at 16:21:45 Local Time

Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"messages":["Connection refused (Connection refused)"],"status":"failure"}']

Builds -
GoCD Version: 18.11.0-8024
Plugin - v1.4.0-RC11

Log snippet -

2018-11-29 09:35:22,646 INFO  [132@MessageListener for PluginNotificationMessageListener] GoNotificationPlugin:78 - api-functional-tests/88/test_runner/1 failed with error
java.net.SocketException: Connection refused (Connection refused)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:435)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
        at in.ashwanthkumar.slack.webhook.service.SlackService.execute(SlackService.java:69)
        at in.ashwanthkumar.slack.webhook.service.SlackService.push(SlackService.java:56)
        at in.ashwanthkumar.slack.webhook.Slack.push(Slack.java:129)
        at in.ashwanthkumar.gocd.slack.SlackPipelineListener.onFailed(SlackPipelineListener.java:58)
        at in.ashwanthkumar.gocd.slack.ruleset.PipelineStatus$3.handle(PipelineStatus.java:31)
        at in.ashwanthkumar.gocd.slack.PipelineListener.handlePipelineStatus(PipelineListener.java:37)
        at in.ashwanthkumar.gocd.slack.PipelineListener.notify(PipelineListener.java:26)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handleStageNotification(GoNotificationPlugin.java:153)
        at in.ashwanthkumar.gocd.slack.GoNotificationPlugin.handle(GoNotificationPlugin.java:93)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:219)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:91)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
        at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ashwanthkumar** [comment]
@abhayda It looks like the plugin is not able to talk to Slack's API. Do you've a proxy or a firewall in place between your GoCD Server and internet? If yes, then it's possibly blocking access to slack's host. That's the reason for the failure.

**Comment by abhayda** [comment]
@ashwanthkumar Thanks for your reply, This issue i am observing only in case of a plugin, 
curl request works fine.

curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello,World!"}' https://hooks.slack.com/services/xxx"

**Comment by ashwanthkumar** [comment]
Can you please share your config file? Please mask away any sensitive information like passwords from that before posting it here.

**Comment by abhayda** [comment]
Its working fine now after commenting out proxy setting from my config file.

#proxy {
  #  hostname = "localhost"
  #  port = "5555"
  #  type = "socks" # acceptable values are http / socks
  #}

Thanks for your help :)
