### ISSUE TITLE
GoCD 19.1.0 error with plugin 1.4.0-RC11

### ISSUE THREAD

**Issue by staker4** [ashwanthkumar/gocd-slack-build-notifier#95]
## Configuration
**GoCD Version** : 19.1.0
**Plugin Version** : 1.4.0-RC11

## Error
Following error occurs :

> Notification update failed for plugin : slack.notifier
> Interaction with plugin with id 'slack.notifier' implementing 'notification' extension failed while requesting for 'stage-status'. Reason: [java/xml/bind/DatatypeConverter]

![error_message](https://user-images.githubusercontent.com/546128/52718811-4c09d200-2f72-11e9-9f8e-fadee1f48b2e.png)

## Context
I just upgraded GoServer from 18.10.0 to 19.1.0 and this error occured.

## Logs

**go-server.log**
![go-server log](https://user-images.githubusercontent.com/546128/52718911-87a49c00-2f72-11e9-9796-76f59a1f5917.png)

**plugin-slack.notifier.log**
![plugin-slack notifier log](https://user-images.githubusercontent.com/546128/52718940-9723e500-2f72-11e9-85bd-feaf8f36ac4e.png)

## Plugin Configuration

I'm using this plugin to push notifications to both Slack and Rocket. This was working fine on GoCD version 18.10.0

```
# Configuration file for gocd-slack-build-notifier
# https://github.com/ashwanthkumar/gocd-slack-build-notifier

gocd.slack {
  login = "..."
  password = "..."

  server-host = "http://...:8153"
  api-server-host = "http://...:8153"

  webhookUrl = "https://hooks.slack.com/services/..."

  # optional fields
  channel = "#gocd"
  display-console-log-links = true
  displayMaterialChanges = true
  process-all-rules = true

  pipelines = [

  # =====
  # SLACK
  # =====

  # ALL except pipeline xxx (because xxx is triggered on every 30 minutes)
  {
    name = "^(?:(?!(?i)xxx).)*$"
    stage = ".*"
    state = "all" # acceptable values are passed, failed, cancelled, building, fixed, broken or all
    webhookUrl = "https://hooks.slack.com/services/..."
  },

  #  FAILED xxx
  {
    name = "xxx"
    stage = ".*"
    state = "failed"
    webhookUrl = "https://hooks.slack.com/services/..."
  },

  # ===========
  # ROCKET.CHAT
  # ===========

  # ALL except pipeline xxx (because xxx is triggered on every 30 minutes)
  {
    name = "^(?:(?!(?i)xxx).)*$"
    stage = ".*"
    state = "all" # acceptable values are passed, failed, cancelled, building, fixed, broken or all
    webhookUrl = "https://rocket.../hooks/..."
  },

  #  FAILED xxx
  {
    name = "xxx"
    stage = ".*"
    state = "failed"
    webhookUrl = "https://rocket.../hooks..."
  }

  ]
}
````

**Comment by ashwanthkumar** [comment]
Thanks for reporting this issue. I'll look into this over the weekend.

Looks like there's some dependency for the plugin which was removed or
conflicting from GoCD server.

**Comment by staker4** [comment]
👍

**Comment by staker4** [comment]
Any news on this issue? Thanks

**Comment by ashwanthkumar** [comment]
Sorry about this. I still haven't got around to check this yet. I'm in a
middle of a job change so my hands pretty full. If you want a would like to
take a stab the issue that would be great. I can help with any specific
questions or issues you might run into three process.

**Comment by arvindsv** [comment]
@staker4 Did you also upgrade Java along with this? Maybe from 8 to 9?

**Comment by arvindsv** [comment]
@staker4 I've made a change which should fix this: https://github.com/arvindsv/gocd-slack-build-notifier/commit/cfbeb0e6ce2b7ac2bd04302c8175c643dc4bb89e

If you're able to try it out and verify that it works, please let me know. If you want me to give you a locally built JAR, I can do that too.

**Comment by arvindsv** [comment]
The short of it is: In Java 9, that class was deprecated and moved to a module. The recommended fix is to depend on it directly.

**Comment by Sepirothni** [comment]
@arvindsv would it be possible to get that locally built JAR for issue validation?

*update* nevermind I was able to get the change to compile locally

**Comment by staker4** [comment]
@arvindsv , I didn't change my version Java. I'm currently at Version 8 Update 161 (build 1.8.0_161-b12).

**Comment by arvindsv** [comment]
@Sepirothni Did it work?

**Comment by arvindsv** [comment]
@staker4 Strange. Maybe they removed it in that version. Not sure. If possible, try the one from this gist: https://gist.github.com/arvindsv/dc5468230b20e96229b1d9a35ed1c484

**Comment by staker4** [comment]
@arvindsv I will try it first thing tomorrow morning. I don't have access to my instance of GOCD at this moment.

**Comment by arvindsv** [comment]
@Sepirothni I see you replied in https://groups.google.com/d/msg/go-cd/_SJY0C4eB2o/Eu5EphX6AgAJ (I assume that's you).

**Comment by Sepirothni** [comment]
@arvindsv yes that's me, yes it is working I just have one pipeline that's being odd but the others appear to be working as desired

**Comment by staker4** [comment]
@arvindsv I installed the RC12 version on my GOCD server (**Windows x64**) instance but with errors. I tried on a clean GOCD server (**Windows x64**) and still getting errors: **zip END header not found**


Here's the **go-server.log** I got :

```console
2019-03-09 14:44:19,377 WARN  [Thread-79] GoPluginDescriptorBuilder:69 - Could not load plugin with jar filename:gocd-slack-notifier-1.4.0-RC12.jar
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1430)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at com.thoughtworks.go.plugin.infra.plugininfo.GoPluginDescriptorBuilder.build(GoPluginDescriptorBuilder.java:58)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:61)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:304)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:217)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:208)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:196)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:181)
2019-03-09 14:44:20,704 ERROR [Thread-79] ZipUtil:160 - Failed to unzip file [lib/jaxb-api-2.3.0.jar] to directory [c:\goserver\plugins_work\gocd-slack-notifier-1.4.0-RC12.jar]
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at com.thoughtworks.go.util.ZipUtil.extractTo(ZipUtil.java:142)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:120)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:127)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.explodePluginJarToBundleDir(DefaultPluginJarChangeListener.java:144)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:96)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:65)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:304)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:217)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:208)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:196)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:181)
2019-03-09 14:44:20,705 WARN  [Thread-79] DefaultPluginJarLocationMonitor:306 - Plugin listener failed
java.lang.RuntimeException: Failed to copy plugin jar plugins\external\gocd-slack-notifier-1.4.0-RC12.jar to bundle location plugins_work\gocd-slack-notifier-1.4.0-RC12.jar
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.explodePluginJarToBundleDir(DefaultPluginJarChangeListener.java:146)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:96)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:65)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:304)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:283)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:217)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:208)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:196)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:181)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at com.thoughtworks.go.util.ZipUtil.extractTo(ZipUtil.java:142)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:120)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:127)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.explodePluginJarToBundleDir(DefaultPluginJarChangeListener.java:144)
	... 9 common frames omitted

```

**Comment by arvindsv** [comment]
@staker4 That is strange. I see that the JAR file is not uploaded properly. :( GitHub gists don't seem to like JAR files.

I've uploaded it to Dropbox: https://www.dropbox.com/s/y5hdsjbr753i155/gocd-slack-notifier-1.4.0-RC12.jar?dl=1

The checksum of the file should be:

```
$ ls -l gocd-slack-notifier-1.4.0-RC12.jar
-rw-r--r-- 1 user group 1,536,309 Mar 12 15:35 gocd-slack-notifier-1.4.0-RC12.jar

$ sha256sum gocd-slack-notifier-1.4.0-RC12.jar
215f85ab22361b3e452d84cc3065810eb138de938244a62c45bcfbb3350cb9cf  gocd-slack-notifier-1.4.0-RC12.jar

$ md5sum gocd-slack-notifier-1.4.0-RC12.jar
b2aa9cadcc691586be3225d6977d7631  gocd-slack-notifier-1.4.0-RC12.jar
```

```
$ unzip -t gocd-slack-notifier-1.4.0-RC12.jar
Archive:  gocd-slack-notifier-1.4.0-RC12.jar
    testing: META-INF/                OK
    testing: META-INF/MANIFEST.MF     OK
    testing: in/                      OK
    testing: in/ashwanthkumar/        OK
    testing: in/ashwanthkumar/gocd/   OK
    testing: in/ashwanthkumar/gocd/slack/   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/   OK
    testing: in/ashwanthkumar/gocd/slack/base/   OK
    testing: lib/                     OK
    testing: views/                   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationMessage$BuildDetailsNotFoundException.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationPlugin$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/SlackPipelineListener$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineRule$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/RulesReader.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$8.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineRule$2.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$7.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$5.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/Rules$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/Rules.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$3.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$4.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineRule.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$6.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/PipelineStatus$2.class   OK
    testing: in/ashwanthkumar/gocd/slack/ruleset/Rules$2.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/BuildCause.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/HttpConnectionUtil.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/ServerFactory.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Stage$1.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Server.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Pipeline.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/MaterialRevision.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Stage.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Material.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Modification.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/History.class   OK
    testing: in/ashwanthkumar/gocd/slack/jsonapi/Job.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationPlugin.class   OK
    testing: in/ashwanthkumar/gocd/slack/SlackPipelineListener$2.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoEnvironment.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationMessage$PipelineInfo.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationMessage.class   OK
    testing: in/ashwanthkumar/gocd/slack/PipelineListener.class   OK
    testing: in/ashwanthkumar/gocd/slack/SlackPipelineListener.class   OK
    testing: in/ashwanthkumar/gocd/slack/GoNotificationMessage$StageInfo.class   OK
    testing: in/ashwanthkumar/gocd/slack/base/AbstractNotificationPlugin.class   OK
    testing: plugin.xml               OK
    testing: lib/config-1.2.1.jar     OK
    testing: lib/httpclient-4.0.1.jar   OK
    testing: lib/jsr305-1.3.9.jar     OK
    testing: lib/commons-logging-1.1.1.jar   OK
    testing: lib/my-java-utils-0.0.9.jar   OK
    testing: lib/google-http-client-1.19.0.jar   OK
    testing: lib/jaxb-api-2.3.0.jar   OK
    testing: lib/commons-io-2.4.jar   OK
    testing: lib/commons-codec-1.3.jar   OK
    testing: lib/slack-java-webhook-0.0.7.jar   OK
    testing: lib/gson-2.3.1.jar       OK
    testing: lib/httpcore-4.0.1.jar   OK
    testing: lib/google-http-client-gson-1.19.0.jar   OK
    testing: views/config.template.html   OK
    testing: reference.conf           OK
    testing: META-INF/maven/          OK
    testing: META-INF/maven/in.ashwanthkumar/   OK
    testing: META-INF/maven/in.ashwanthkumar/gocd-slack-notifier/   OK
    testing: META-INF/maven/in.ashwanthkumar/gocd-slack-notifier/pom.xml   OK
    testing: META-INF/maven/in.ashwanthkumar/gocd-slack-notifier/pom.properties   OK
No errors detected in compressed data of gocd-slack-notifier-1.4.0-RC12.jar.
```

**Comment by staker4** [comment]
@arvindsv it works again. Thank you so much :smiley:

**Comment by arvindsv** [comment]
Great! I've opened #96 for @ashwanthkumar to merge and release.

**Comment by ashwanthkumar** [comment]
Thanks @arvindsv for the PR. I've created a [new release](https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/tag/v1.4.0-RC12) with the above changes.
